### ISSUE TITLE
issue in favfreak.py file

### ISSUE THREAD

**Issue by ghost** [devanshbatham/FavFreak#11]
Traceback (most recent call last):
  File "/root/tools/FavFreak/favfreak.py", line 85, in <module>
    a,urls= main() # unindented this
  File "/root/tools/FavFreak/favfreak.py", line 21, in main
    if line.strip()[-1] == "/":
IndexError: string index out of range

**Comment by srand2** [comment]
Traceback (most recent call last):
  File "/opt/Recon/FavFreak/favfreak.py", line 85, in <module>
    a,urls= main()
  File "/opt/Recon/FavFreak/favfreak.py", line 21, in main
    if line.strip()[-1] == "/":
IndexError: string index out of range

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "favfreak.py", line 85, in <module>
    a,urls= main()
  File "favfreak.py", line 21, in main
    if line.strip()[-1] == "/":
IndexError: string index out of range

**Comment by HackMoD-InfoSec** [comment]
Traceback (most recent call last):
  File "/vv/c/tools/FavFreak/favfreak.py", line 85, in <module>
    a,urls= main()
  File "/vv/c/tools/FavFreak/favfreak.py", line 21, in main
    if line.strip()[-1] == "/":
IndexError: string index out of range

**Comment by karim-jpg** [comment]
use python3 ? it's work for me

**Comment by Dark-Night0** [comment]
Hi Regarding that problem
```
Traceback (most recent call last):
File "/root/tools/FavFreak/favfreak.py", line 85, in
a,urls= main() # unindented this
File "/root/tools/FavFreak/favfreak.py", line 21, in main
if line.strip()[-1] == "/":
IndexError: string index out of range
```
This problem is caused by a default newline in the file.
You can filter out the blank line in the file, or
go to line 21 and replace it with this line `if line.strip() and line.strip()[-1] == "/":`
